local f = io.open('Hacker.lua', "rb")
local content = f:read("*all")
f:close()
os.execute('killall -9 Hacker.sh')
os.execute('killall -9 tg')
os.execute('rm -rf Hacker.lua')
os.execute('git reset --hard origin/master')
os.execute('git pull')
local fi = io.open('Hacker.lua', "w+")
fi:write(tostring(content))
fi:close()
os.execute('chmod 777 tg && chmod 777 Hacker.sh')
os.execute('screen ./Hacker.sh')
